version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    ports:
      - "8000:80"
      - "22:22"
      - "443:443"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config: