### code review request
POST http://localhost/code/review
Content-Type: application/json
API-Key: 123456

{
    "prompt" : "```python from pydantic import BaseModel class ErrorResponse(BaseModel): detail: str     class PromptRequest(BaseModel): prompt: str```"
}


### tastk status 
### tasks 뒤에 task id 사용
GET http://localhost/tasks/cce74b02-71d3-44d6-aca9-b58ec09ecbf5
API-Key: 123456


12037248-5317-4dfb-95b7-160c076edaa9
cce74b02-71d3-44d6-aca9-b58ec09ecbf5
8461a9f7-b105-49a7-bce7-15e5e4c93930