### code review request
POST http://localhost/code/review
Content-Type: application/json
API-Key: 123456

{
    "prompt" : "```python from pydantic import BaseModel class ErrorResponse(BaseModel): detail: str     class PromptRequest(BaseModel): prompt: str```"
}


### tastk status 
### tasks 뒤에 task id 사용
GET http://localhost/tasks/6d571157-75d0-4fbb-b446-261d67966fe2
API-Key: 123456


6d571157-75d0-4fbb-b446-261d67966fe2
441e7226-ef05-4567-9598-c45dce43ce59