### code review request
POST http://localhost/code/review
Content-Type: application/json
API-Key: 123456

{
    "prompt" : "```python from pydantic import BaseModel class ErrorResponse(BaseModel): detail: str     class PromptRequest(BaseModel): prompt: str```"
}


### tastk status 
### tasks 뒤에 task id 사용
GET http://localhost/tasks/2b79eb42-d1a6-41d1-a7f6-3e9dcf6fa98b
API-Key: 123456


7002cf7d-4f75-4195-8aac-628769813d48
2668f123-7a48-402a-ae8b-04b37cbfd153