version: '3.9'

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/app/.env
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - ollama      
      - redis
      - celery
  
  redis:
    image: "redis:alpine"
    networks:
      - app_network

  celery:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./fastapi:/app
    env_file:
      - ./fastapi/app/.env
    depends_on:
      - redis
    networks:
      - app_network

  flower:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - fastapi
      - redis
      - celery
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"      
    depends_on:
      - fastapi
    networks:
      - app_network
      - shared_network
      - report_network

  ollama:
    image: ollama/ollama:latest    
    environment:
      - API_KEY=your_ollama_api_key  # Replace or set in a safer way        
    command: ["serve"]
    networks:
      - app_network    

networks:
  app_network:
    driver: bridge
  shared_network:
    external: true
  report_network:
    external: true  