version: '3.9'

services:  
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - "9000:80"
      - "9022:22"
      - "9443:443"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    networks:      
      - shared_network

  file_server:
    build:
      context: ./file_server
      dockerfile: Dockerfile
    container_name: file_server
    ports:
      - "9501:8000"
      - "9502:8501"
    volumes:
      - ./file_server/app:/app
      - ./file_server/supervisord.conf:/app/supervisord.conf
    networks:
      - file_network

  file_nginx:
    build:
      context: ./file_nginx
      dockerfile: Dockerfile
    container_name: file_nginx
    ports:
      - "9600:80"
    networks:
      - file_network
      - report_network

  file_db:
    build:
      context: ./file_db
      dockerfile: Dockerfile
    container_name: file_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: file_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "9700:3306"
    volumes:
      - ./file_db/init:/docker-entrypoint-initdb.d
    networks:
      - file_network


volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:

networks:
  shared_network:
    external: true  
  file_network:
    driver: bridge
  report_network:
    external: true  
