version: '3.9'

services:  
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    ports:
      - "9000:80"
      - "9022:22"
      - "9443:443"
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    networks:      
      - shared_network

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:

networks:
  shared_network:
    external: true  